---
- hosts: webservers
  become: yes
  tasks:
    - name: Create Virtualenv
      command:
        cmd: virtualenv /var/virtualenv/projeto02 -p python3.6

    - name: Create directory app
      ansible.builtin.file:
        path: /var/www/projeto02
        state: directory
        mode: '0755'

    - name: Create requirements
      shell: echo Django > /var/www/projeto02/requirements.txt

    - name: Install Django
      pip:
        requirements: /var/www/projeto02/requirements.txt
        virtualenv: /var/virtualenv/projeto02

    - name: Startup Django 
      shell: /var/virtualenv/projeto02/bin/django-admin startproject projeto02 /var/www/projeto02/

    - name: Replace ALLOWED_HOSTS
      ansible.builtin.replace:
        path: /var/www/projeto02/projeto02/settings.py
        regexp: '^ALLOWED_HOSTS = \[\]'
        replace: 'ALLOWED_HOSTS = ["192.168.50.44"]'

    - name: Migrate
      django_manage:
        command: migrate
        app_path: /var/www/projeto02
        virtualenv: /var/virtualenv/projeto02

    - name: Runserver
      django_manage:
        command: runserver 0.0.0.0:8000 
        app_path: /var/www/projeto02
        virtualenv: /var/virtualenv/projeto02
