---
- name: setup basic
  hosts: webserver
  tasks:
    - name: Install  epel-release
      yum:
        name: epel-release
        state: present

    - name: Copy Repo for PHP74
      ansible.builtin.copy:
        src: remi-release-8.rpm
        dest: /tmp/remi-release-8.rpm

    - name: Install Repo Local
      command: yum install /tmp/remi-release-8.rpm -y
      ignore_errors: yes

    - name:  Install Utils
      yum:
        name:
          - vim
          - wget
          - net-tools

    - name: Upgrade All Packages
      yum:
        name: "*"
        state: latest

    - name: Reset for repo PHP old
      command: yum module reset php

    - name: Enable PHP74
      yum:
        enablerepo: "php:remi-7.4"
        name: php74

    - name: Install PHP74
      yum:
        name:
          - php74
          - php74-php-common
          - php74-php-cli
          - php74-php-fpm
        state: present

    - name: install httpd
      yum:
        name: httpd
        state: present


    - name: Copyng Load.php
      ansible.builtin.copy:
        src: load.php
        dest: /tmp/load.php

    - name: Load config PHP-FPM from Httpd
      ansible.builtin.shell: cat /tmp/load.php >> /etc/httpd/conf/httpd.conf

    - name: Ensure Httpd is running
      service:
        name: httpd
        state: started

    - name: Open port 80 for httpd access
      firewalld:
        service: http
        permanent: true
        state: enabled

    - name: Restart the firewalld service to load in the firewall changes
      service:
        name: firewalld
        state: restarted

    - name: Instalation Mysql 8.0
      yum:
        name: mysql-server
        state: present

    - name: Ensure Mysql is Running
      service:
        name: mysqld
        state: started

    - name: Copyng index.php
      ansible.builtin.copy:
        src: index.php
        dest: /var/www/html/index.php
        owner: apache
        group: apache

    - name: Install git
      yum:
        name: git
        state: present

    - name: Deploy git checkout
      ansible.builtin.git:
        repo: git@github.com:eribertos/Ansible.git
        dest: /var/site/

    - name: Validate Composer checksum
      get_url:
        dest: /usr/src/
        url: https://getcomposer.org/installer
      become: yes

    - name: Download and install Composer
      shell: curl -sS https://getcomposer.org/installer | php74
      args:
        chdir: /usr/src/
        creates: /usr/local/bin/composer
        warn: false
      become: yes

    - name: Add Composer to global path
      copy: 
        dest: /usr/local/bin/composer
        group: root
        mode: '0755'
        owner: root
        src: /usr/src/composer.phar
        remote_src: yes
      become: yes
